### ISSUE TITLE
点击悬浮窗外部空白区域 悬浮窗消失怎么实现

### ISSUE THREAD

**Issue by Jasperben** [kongxiaojun/EasyFloat#11]
点击悬浮窗外部空白区域 悬浮窗消失怎么实现

**Comment by kongxiaojun** [comment]
悬浮窗本身无法监听浮窗外部的点击事件，如果是应用内的浮窗可以在应用内检测到后调用EasyFloat.dismiss或者EasyFloat.hide方法实现。
