### ISSUE TITLE
请教一下怎么实现监听浮窗在静止一会后自动变小并吸附在屏幕边缘，点击的时候再恢复显示在原来的位置，像360那个浮球一样

### ISSUE THREAD

**Issue by Tipsyume** [kongxiaojun/EasyFloat#3]

**Comment by kongxiaojun** [comment]
目前EasyFloat没有此功能，您可以自行实现。大概逻辑如下：
1. EasyFloat创建第一个悬浮窗
2. 静止后启动定时器，时间到后EasyFloat创建吸附在边缘的悬浮窗，并因此第一个悬浮窗
3. 点击后显示第一个悬浮窗，隐藏小球悬浮窗

**Comment by Tipsyume** [comment]
> 目前EasyFloat没有此功能，您可以自行实现。大概逻辑如下：
> 
> 1. EasyFloat创建第一个悬浮窗
> 2. 静止后启动定时器，时间到后EasyFloat创建吸附在边缘的悬浮窗，并因此第一个悬浮窗
> 3. 点击后显示第一个悬浮窗，隐藏小球悬浮窗

谢谢分享
