### ISSUE TITLE
通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

### ISSUE THREAD

**Issue by 13120241790** [kongxiaojun/EasyFloat#7]
通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去，尝试设置了一些 WindowManager 的属性没有用

**Comment by kongxiaojun** [comment]
开始录制屏幕的时候调用hide方法隐藏悬浮窗即可。

**Comment by 13120241790** [comment]
想要的效果是录屏功能 别把悬浮球录制进去了 用户可以在桌面上看到悬浮球 但是录制出来的内容不包含悬浮球 @kongxiaojun

**Comment by kongxiaojun** [comment]
这个无法实现，MediaProjection无法排除指定的View
