### ISSUE TITLE
建议添加图层优先级显示设置

### ISSUE THREAD

**Issue by hdinson** [kongxiaojun/EasyFloat#8]
你好,目前EasyFloat用很爽,但是涉及到了一个问题,就是多个悬窗重叠的时候,希望添加一个图层优先级显示的设置.

**Comment by Tipsyume** [comment]
这个需求不错，我现在是通过重新创建来防止被遮挡的问题

**Comment by kongxiaojun** [comment]
Android原生不支持优先级，后添加的优先级高，建议你将优先级高的悬浮窗放到后面添加。
